### ISSUE TITLE
better detection of roam studio

### ISSUE THREAD

**Issue by paulovieira** [paulovieira/roam-reference-path#18]
If the roam studio extension is also loaded, roam-reference-path must do some adjustments to to the top offset. This is implemented since roam studio was launched, however the automatic detection of roam studio is not working well, as can be seen in this screenshot:

![Screenshot_2023-03-14_16-20-28](https://user-images.githubusercontent.com/2184309/225071512-8e9946ba-f602-48da-bc22-3b36b212006b.png)

**Comment by Bo-Feng-1024** [comment]
Hi,

It seems that this issue has not been solved yet. The screenshot showase the situation. Could you please help me solve it? Thank you! 
![image](https://github.com/user-attachments/assets/88ef7915-ff0d-45ed-8be9-89aed20916ed)

**Comment by paulovieira** [comment]
The commits mentioned above will now detect if Roam Studio is present and do the necessary adjustments. 

However there is another situation where those adjustments are not enough: when the block is H1/H2/H3, Roam Studio will add more styles (`margin-top`, `margin-bottom`) to children element, which ruin our computation for the height.

![Screenshot from 2024-08-20 02-55-46](https://github.com/user-attachments/assets/8c9263ff-9679-4548-b14d-c91448d5f1e7)

A possible solution: when computing the height, also take into account those elements that have the extra height, which in this case are `<div class="controls"><div>`. In a normal situation we have `current.y - previous.y = 0`, but not here. That difference seems to be what we need to have the correct height.
